

import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { AntdRegistry } from "@ant-design/nextjs-registry";
import { ConfigProvider } from "antd";
import theme from "../../config/themeConfig";
import AntdCompatPatch from "./_antd-compat";
import AppLayout from "./AppLayout";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Batch Track",
  description: "Generated by Roni",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        <AntdCompatPatch>
          <ConfigProvider theme={theme}>
            <AntdRegistry>
              <AppLayout>{children}</AppLayout>
            </AntdRegistry>
          </ConfigProvider>
        </AntdCompatPatch>
      </body>
    </html>
  );
}
